# syntax=docker/dockerfile:1.4
FROM docker.io/osrf/ros:jazzy-desktop
SHELL ["/bin/bash", "-c"]
ENV MY_ROS_DISTRO=jazzy

ENV DEBIAN_FRONTEND=noninteractive

# 1. System Dependencies
RUN apt-get update && apt-get install -y git python3-pip vim tree python3-venv\
    lua5.1 liblua5.1.0-dev luarocks cmake build-essential ros-dev-tools software-properties-common\
    lsb-release libpcre3-dev libfmt-dev\
    ros-$MY_ROS_DISTRO-ament-cmake \
    ros-$MY_ROS_DISTRO-ament-cmake-core \
    python3-colcon-common-extensions

RUN luarocks install dkjson
RUN luarocks install jsonschema

# 2. Fake Root Permissions
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd


#3. Build and Install Boost (Heavy Operation)

# Define the version and path at the top (makes it easy to update)
ENV BOOST_VERSION=1.89.0
ENV BOOST_189_ROOT=/opt/boost_${BOOST_VERSION}


# Set working directory
WORKDIR /tmp
RUN wget -O boost_install.tar.gz "https://sourceforge.net/projects/boost/files/boost/1.89.0/boost_1_89_0.tar.gz/download" && \
    tar -xvzf boost_install.tar.gz && \
    rm boost_install.tar.gz && \
    cd boost_$(echo ${BOOST_VERSION} | tr . _) && \
    ./bootstrap.sh --prefix=${BOOST_189_ROOT} && \
    ./b2 -j$(nproc) install && \
    cd /tmp && \
    rm -rf boost*

    
# 4. Python Packages (System-wide)
RUN pip3 install --break-system-packages jsonref jsonschema colorama requests
    # setuptools==58.2.0 \

# 5. Build the BASE Workspace in /opt (Accessible to all users)
# We use /opt because Distrobox does NOT overwrite this folder.
ENV BASE_WS=/opt/ros2_crospi_ws
RUN mkdir -p $BASE_WS/src
WORKDIR $BASE_WS

# RUN git clone --recursive https://github.com/Robotics-Research-Group-KUL/crospi.git src/crospi 

RUN git clone --recursive https://github.com/Robotics-Research-Group-KUL/crospi.git src/crospi \
&& git clone --recursive https://github.com/Robotics-Research-Group-KUL/betfsm.git src/betfsm

# Remove crospi_application_template directory from the crospi repository to avoid build issues
# RUN rm -rf src/crospi/crospi_application_template

RUN rosdep init || true && \
    rosdep update

# Install dependencies and build
RUN apt-get update && \
    rosdep init || true && \
    rosdep update && \
    source /opt/ros/$MY_ROS_DISTRO/setup.bash && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install && \
    rm -rf /var/lib/apt/lists/*

# 6. Global Sourcing
# We add the source command to the GLOBAL bashrc so every user has it automatically
RUN echo "source $BASE_WS/install/setup.bash" >> /etc/bash.bashrc

WORKDIR /
CMD ["/usr/bin/bash"]