# syntax=docker/dockerfile:1.4
FROM docker.io/osrf/ros:rolling-desktop
ENV MY_ROS_DISTRO=rolling

ENV DEBIAN_FRONTEND=noninteractive

# 1. System Dependencies
RUN apt-get update && apt-get install -y git python3-pip vim tree python3-venv \
    lua5.1 liblua5.1.0-dev luarocks cmake build-essential ros-dev-tools software-properties-common \
    lsb-release libfmt-dev \
    libssl-dev \
    ca-certificates \
    curl \
    procps \
    passwd \
    adduser \
    libcap2-bin \
    python3-numpy \
    python3-scipy \
    python3-pandas \
    python3-matplotlib \
    python3-colorama \
    python3-requests \
    python3-uvicorn \
    python3-websockets \
    python3-fastapi \
    openssh-client \
    openssh-client \
    tmux wget \
    libgl1-mesa-dri \
    libgl1 \
    ipython3
    #  ros-$MY_ROS_DISTRO-plotjuggler-ros is not yet available for lyrical.

# lrexlib-pcre (luarock dependency of jsonschema) needs pcre.h from libpcre3-dev.
# Build and install PCRE 8.45 from source (libpcre3 dropped in Ubuntu 26.04)
RUN wget https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz && \
    tar xzf pcre-8.45.tar.gz && \
    cd pcre-8.45 && \
    ./configure && \
    make && \
    make install && \
    ldconfig && \
    cd .. && rm -rf pcre-8.45 pcre-8.45.tar.gz


RUN luarocks install net-url && \
    luarocks install dkjson && \
    luarocks install lrexlib-pcre PCRE_DIR="/usr/local" && \
    luarocks install jsonschema

# 2. Fake Root Permissions
RUN echo "%sudo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd


#3. Build and Install Boost (Heavy Operation)

# Define the version and path at the top (makes it easy to update)
ENV BOOST_VERSION=1.89.0
ENV BOOST_189_ROOT=/opt/boost_${BOOST_VERSION}


# Build and Install using the variable
WORKDIR /tmp
RUN wget -O boost.tar.gz "https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz/download" \
&& tar -xzf boost.tar.gz \
&& cd boost_$(echo ${BOOST_VERSION} | tr . _) \
&& ./bootstrap.sh --prefix=${BOOST_189_ROOT} \
&& ./b2 -j$(nproc) install \
&& cd /tmp \
&& rm -rf boost*

# Update paths so the system and CMake can find it
ENV LD_LIBRARY_PATH=${BOOST_189_ROOT}/lib:${LD_LIBRARY_PATH}

# Ensure the runtime linker knows about the new path
RUN echo "${BOOST_189_ROOT}/lib" > /etc/ld.so.conf.d/boost_custom.conf && ldconfig

# 4. Python Packages (System-wide)
RUN pip3 install --break-system-packages --no-cache-dir --ignore-installed jsonref jsonschema
    # setuptools==58.2.0 \

# Nice-to-have Python Packages
RUN pip3 install --break-system-packages --ignore-installed plotly

# 5. Build the BASE Workspace in /opt (Accessible to all users)
# We use /opt because Distrobox does NOT overwrite this folder.
ENV BASE_WS=/opt/ros2_crospi_ws
RUN mkdir -p $BASE_WS/src
WORKDIR $BASE_WS

# RUN git clone --recursive https://github.com/Robotics-Research-Group-KUL/crospi.git src/crospi 

RUN git clone --recursive https://github.com/Robotics-Research-Group-KUL/crospi.git src/crospi \
&& git clone --recursive https://github.com/Robotics-Research-Group-KUL/betfsm.git src/betfsm

# Remove crospi_application_template directory from the crospi repository to avoid build issues
# RUN rm -rf src/crospi/crospi_application_template

RUN rosdep init || true && \
    rosdep update

# Install dependencies and build
RUN /bin/bash -c '\
    apt-get update && \
    (rosdep init || true) && \
    rosdep update && \
    source /opt/ros/$MY_ROS_DISTRO/setup.bash && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install && \
    rm -rf /var/lib/apt/lists/* \
'

# 6. Global Sourcing
# We add the source command to the GLOBAL bashrc so every user has it automatically
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash " >> /etc/bash.bashrc
RUN echo 'source $BASE_WS/src/crospi/custom_aliases_crospi.sh' >> /etc/bash.bashrc
RUN echo "source $BASE_WS/install/setup.bash" >> /etc/bash.bashrc

WORKDIR /
CMD ["/usr/bin/bash"]