name: lyrical Build and Test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'images/**'
      - '**/*.png'
      - '**/*.jpg'
      - '.gitignore'
      - 'Containerfile'
      - '.podman/**'
      - '.github/workflows/podman-*.yml'
      - '.github/workflows/podman-*.yaml'
  pull_request:
  workflow_dispatch:
  release:
    types: [created, published]
  workflow_run:
    workflows: ["Docker test lyrical - Build & Push Docker Images for ROS2 lyrical"]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  build_and_test_ros2_lyrical:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robotics-research-group-kul/crospi-build-test:lyrical
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure GitHub token for HTTPS cloning
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        env:
          BOOST_189_ROOT: /opt/boost/1.89.0
        with:
          package-name: etasl_wrapper crospi_core crospi_interfaces crospi_default_plugins 
          target-ros2-distro: lyrical
          skip-tests: true
          coverage-result: false
