name: Podman rolling - Build & Push Images for ROS2 rolling

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
  pull_request:
  release:
    types: [created, published]

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    name: Build & Push Base Image (Podman)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          podman build \
            -f .podman/user_containers/rolling/Containerfile \
            -t ghcr.io/robotics-research-group-kul/crospi-betfsm-podman:ros2-rolling \
            .

      - name: Push image
        run: |
          podman push ghcr.io/robotics-research-group-kul/crospi-betfsm-podman:ros2-rolling